name: schema_org
description: "A JSON-LD library with Flutter/Dart types for Schema.org vocabulary."
version: 1.0.3
homepage: https://github.com/oddbit/flutter-schema-org

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  build_runner: ^2.4.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
