name: schema_parser
description: A Dart command-line tool to parse schema files.
version: 0.1.0

executables:
  schema_parser: bin/schema_parser.dart

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
