name: schema_parser
description: A Dart command-line tool to parse schema files.
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.3.0
  test: ^1.25.2

executables:
  schema_parser: schema_parser