name: schema_parser
description: A Dart command-line tool to parse schema files.
version: 0.1.0

environment:
  sdk: ^3.3.2

dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
